---
# Stop service
- name: Stop apache
  service:
    name: httpd
    state: stopped
    enabled: no

# Disable ports 80/443 on firewall
- name: Configure firewall
  firewalld:
    service: "{{ item }}"
    permanent: yes
    state: disabled
  with_items:
    - http
    - https
  notify:
  - Reload firewall

# Check if firewall is running
- name: Check firewall service status
  service_facts:
  register: services_state
