---
# Stop Apache web services
 
- name: Stop apache
  service:
    name: httpd
    state: stopped
    enabled: no

- name: Configure firewall
  firewalld:
    service: "{{ item }}"
    permanent: yes
    state: disabled
  with_items:
    - http
    - https
  notify:
  - Reload firewall

- name: Check firewall service status
  service_facts:
  register: services_state
