---
# Stop apache service 
- name: Stop apache
  service:
    name: httpd
    state: stopped
    enabled: no

# Disable http/https ports on firewall
- name: Configure firewall
  firewalld:
    service: "{{ item }}"
    permanent: yes
    state: disabled
  with_items:
    - http
    - https
  notify:
  - Reload firewall

# Check if firewall is running
- name: Check firewall service status
  service_facts:
  register: services_state

# Uninstall package
- name: Ensure apache is removed
  yum:
    name: ['httpd', 'mod_ssl']
    state: absent
